"""Collection of random phrases
"""

from random import choice


QUOTES = [
    '"To be, or not to be: that is the question." – Hamlet',
    '"All the world’s a stage, and all the men and women merely players." – As You Like It',
    '"A rose by any other name would smell as sweet." – Romeo and Juliet',
    '"The course of true love never did run smooth." – A Midsummer Night’s Dream',
    '"Et tu, Brute?" – Julius Caesar',
    '"It is a truth universally acknowledged, that a single man in possession of a good fortune, must be in want of a wife." – Pride and Prejudice',
    '"I am excessively diverted." – Pride and Prejudice',
    '"There is no charm equal to tenderness of heart." – Sense and Sensibility',
    '"You must be the best judge of your own happiness." – Emma',
    '"To Mr. John Knightley, I am under an obligation to myself to say, that I am a very agreeable companion." – Emma',
    '"It was the best of times, it was the worst of times..." – A Tale of Two Cities',
    '"Please, sir, I want some more." – Oliver Twist',
    '"God bless us, every one!" – A Christmas Carol',
    '"The one thing that is important is to keep moving." – David Copperfield',
    '"There is nothing in the world so irresistibly contagious as laughter and good humor." – A Christmas Carol',
    '"I am no bird; and no net ensnares me: I am a free human being with an independent will." – Jane Eyre',
    '"I have to tell you that I am a very agreeable person." – Jane Eyre',
    '"Life is always a little uncertain." – Jane Eyre',
    '"Whatever our souls are made of, his and mine are the same." – Wuthering Heights',
    '"I cannot live without my soul." – Wuthering Heights',
    '"I wish I were a girl again, half savage and hardy, and free." – Wuthering Heights',
    '"The intense horror of nightmare came over me." – Wuthering Heights',
    '"It is never too late to be what you might have been." – Middlemarch',
    '"The only way to get rid of temptation is to yield to it." – Middlemarch',
    '"We are all fools in love." – Middlemarch',
    '"The world is full of magic things, patiently waiting for our senses to grow sharper." – Middlemarch',
    '"It is better to be alone than in bad company." – Middlemarch',
    '"It’s no use going back to yesterday, because I was a different person then." – Alice’s Adventures in Wonderland',
    '"Curiouser and curiouser!" – Alice’s Adventures in Wonderland',
    '"The best way to explain it is to do it." – Alice’s Adventures in Wonderland',
    '"We’re all mad here." – Alice’s Adventures in Wonderland',
    '"I have to tell you that I am very much in love with you." – Strange Case of Dr Jekyll and Mr Hyde',
    '"The world is full of magic things, patiently waiting for our senses to grow sharper." – Strange Case of Dr Jekyll and Mr Hyde',
    '"The only thing we have to fear is fear itself." – Treasure Island',
    '"I have to tell you that I am a very agreeable person." – Treasure Island',
    '"The rain is falling all around, it falls on field and tree..." – Treasure Island',
    '"We are all in the gutter, but some of us are looking at the stars." – Lady Windermere’s Fan',
    '"To live is the rarest thing in the world. Most people exist, that is all." – The Soul of Man under Socialism',
    '"Experience is simply the name we give our mistakes." – The Picture of Dorian Gray',
    '"I have nothing to declare except my genius." – The Picture of Dorian Gray',
    '"The truth is rarely pure and never simple." – The Importance of Being Earnest',
    '"I have to tell you that I am very much in love with you." – The Pilgrim’s Progress',
]
PROGRAMMING = [
    "A 'pure' data structure in functional programming means that it is immutable and has no side effects.",
    "A `Lens` allows you to focus on a specific part of a data structure, enabling both getting and setting values in a functional way.",
    "A `Tuple` is a fixed-size collection of elements, potentially of different types, used to group related values.",
    "A functor is a type that implements a `map` operation, applying a function to values within the functor context.",
    "A lambda function is an anonymous function that can be used for short-lived operations.",
    "A monad is a design pattern used to handle computations in a functional programming paradigm, particularly to manage side effects.",
    "A monoid can be defined in any category where there is an associative binary operation and an identity element.",
    "Currying is a technique of transforming a function that takes multiple arguments into a sequence of functions each taking a single argument.",
    "Endofunctors are functors that map a category to itself, preserving the structure of the category.",
    "Endofunctors are used in category theory to describe mappings within the same category, such as mapping types to types.",
    "Function composition is the process of combining two or more functions to produce a new function.",
    "Functional programming emphasizes the use of functions and avoids changing state or mutable data.",
    "Functional programming languages like Haskell and Scala are designed around the principles of immutability and pure functions.",
    "Functional programming languages often use algebraic data types like `Union` and `Intersection` types to model complex data structures.",
    "Functional programming languages often use pattern matching to decompose data structures in a declarative way.",
    "Functional programming often leverages algebraic data types like `Either`, `Maybe`, and `Tuple` to model various kinds of data.",
    "Functional programming often uses immutable data structures to ensure that data is not modified by multiple threads simultaneously.",
    "Higher-order functions are functions that take other functions as arguments or return functions as results.",
    "Immutability means that once a data structure is created, it cannot be changed.",
    "Immutable data structures can help prevent issues related to concurrent programming and data races.",
    "In Clojure, immutability is a core principle, with data structures designed to be persistent and immutable.",
    "In Haskell, `Data.Map` is an immutable map data structure that provides efficient key-value lookups.",
    "In Haskell, `Typeclasses` are a way to define generic interfaces that can be implemented for different types.",
    "In Haskell, the `Maybe` type is similar to `Option`, representing values that may or may not be present.",
    "In JavaScript, higher-order functions like `map`, `filter`, and `reduce` are frequently used for functional programming.",
    "In JavaScript, the `Promise` object is a type of monad that represents a value which may be available now, or in the future, or never.",
    "In Python, the `functools` module provides tools for functional programming, such as `partial`, `reduce`, and `lru_cache`.",
    "In Scala, `case classes` provide a convenient way to define immutable data structures with automatic support for pattern matching.",
    "In Scala, the `Option` type represents a value that may or may not be present, offering a way to avoid null references.",
    "In category theory, a functor is a structure-preserving map between categories.",
    "In functional programming, `memoization` is a technique for caching function results to improve performance by avoiding redundant computations.",
    "In functional programming, `set theory` concepts like `union`, `intersection`, and `difference` are often used to model data transformations.",
    "In functional programming, `tail-call optimization` can be used to optimize recursive functions, preventing stack overflow errors.",
    "In functional programming, data transformations are often performed using function composition.",
    "In functional programming, functions are first-class citizens, meaning they can be passed as arguments, returned from other functions, and assigned to variables.",
    "In functional programming, recursion is often used instead of loops for iteration.",
    "In functional programming, side effects are often handled using monads to ensure that they do not break referential transparency.",
    "In mathematics, a `functor` maps between categories, preserving the structure of the category.",
    "In mathematics, a functor is a mapping between categories that preserves the structure of the categories.",
    "In object-oriented programming, immutability can be achieved by making all fields of a class final and only providing getters.",
    "In programming, `tail recursion` optimization can help avoid stack overflow issues by reusing stack frames for recursive function calls.",
    "In type theory, a functor is a mapping between categories that preserves the categorical structure.",
    "Lazy evaluation defers the evaluation of an expression until its value is actually needed, which can improve performance and enable infinite data structures.",
    "Monads can be thought of as a way to chain computations together while managing side effects.",
    "Monads often come with three main operations: `return` (or `pure`), `bind` (or `flatMap`), and `>>=` (the bind operator).",
    "Monoids are algebraic structures with an associative binary operation and an identity element.",
    "Pure functions always produce the same output given the same input and have no side effects.",
    "The `Applicative` functor extends the `Functor` by allowing functions that are themselves wrapped in a context to be applied to values wrapped in the same context.",
    "The `Arrow` typeclass in Haskell generalizes monads and provides a way to work with computations that have a directional flow.",
    "The `Arrow` typeclass in Haskell provides a way to work with computations that have a directional flow, generalizing both `Functor` and `Applicative`.",
    "The `Async` monad is used to handle asynchronous computations, providing a way to work with operations that complete in the future.",
    "The `Bifunctor` typeclass extends `Functor` to work with types that have two parameters.",
    "The `Cont` monad (continuation monad) represents computations in continuation-passing style, allowing control flow to be manipulated.",
    "The `Continuation` monad provides a way to represent computations in continuation-passing style, allowing for advanced control flow mechanisms.",
    "The `Either` type represents a value that can be one of two possible types, often used for error handling.",
    "The `Filter` function creates a list of elements for which a given function returns True.",
    "The `Freer` monad is a generalization of monads that allows for the definition of effects and operations in a modular way.",
    "The `Functor` typeclass in Haskell provides a way to map functions over wrapped values, preserving the structure of the functor.",
    "The `Functor` typeclass in Haskell provides a way to map functions over wrapped values.",
    "The `IO` monad in Haskell encapsulates input/output operations, allowing functional programming to interact with the outside world.",
    "The `IO` monad in Haskell provides a way to perform input and output operations while maintaining functional purity.",
    "The `IO` monad provides a way to handle side effects while maintaining functional purity.",
    "The `Lazy` data structure allows for the delayed evaluation of values, enabling the creation of infinite data structures.",
    "The `Lens` library provides tools for functional programming to access and modify nested data structures in an immutable way.",
    "The `List` monad represents computations that can return multiple results, allowing for chaining operations on lists.",
    "The `Map` function applies a given function to each item of an iterable and returns a list of results.",
    "The `Monad Transformer` stack allows you to combine different monads to work with multiple effects simultaneously.",
    "The `Monad` typeclass extends `Functor` by allowing chaining of computations and managing side effects.",
    "The `Monad` typeclass provides a way to chain computations together in a functional programming context.",
    "The `Monoid` typeclass in Haskell provides a way to combine values using an associative binary operation and an identity element.",
    "The `Option` type is used to represent optional values, encapsulating the presence or absence of a value.",
    "The `Reader` monad allows functions to implicitly",
    "The `Reader` monad allows functions to implicitly access shared read-only state.",
    "The `Reader` monad is useful for dependency injection, allowing computations to access read-only shared state without explicitly passing it around.",
    "The `Reduce` function applies a binary function to a sequence, reducing it to a single cumulative result.",
    "The `State` monad encapsulates stateful computations, allowing you to thread state through computations in a functional way.",
    "The `State` monad is used to model computations that involve changing state, allowing state to be threaded through computations in a functional way.",
    "The `Stream` data structure provides a way to represent sequences of data that can be processed lazily, one element at a time.",
    "The `Task` type represents a computation that may be performed asynchronously and can be used to model complex workflows.",
    "The `Writer` monad is used to accumulate results or logs alongside computations.",
    "The `Writer` monad provides a way to accumulate results or logs alongside computations, supporting the combination of results.",
    "The `compose` function takes two functions as arguments and returns a new function that is the composition of the two.",
    "The concept of 'referential transparency' means that expressions can be replaced with their values without changing the program’s behavior.",
    "Object-oriented programming (OOP) focuses on objects and classes, encapsulating data and behavior into reusable components.",
    "Encapsulation hides the internal state of an object and only exposes a controlled interface.",
    "Inheritance allows a class to inherit properties and methods from another class, promoting code reuse.",
    "Polymorphism enables objects of different classes to be treated as objects of a common superclass.",
    "Abstraction involves hiding complex implementation details and showing only the essential features of an object.",
    "Composition allows the construction of complex objects by combining simpler ones, often preferred over inheritance for flexibility.",
    "In a class-based language, a class defines the structure and behavior of objects, while instances are concrete realizations of classes.",
    "In an interface-based language, an interface defines a contract that classes must follow without providing implementation details.",
    "Multiple inheritance allows a class to inherit from more than one parent class, though it can introduce complexity and ambiguity.",
    "In contrast, single inheritance restricts a class to inherit from only one parent class, simplifying the class hierarchy.",
    "Design patterns are reusable solutions to common software design problems, such as Singleton, Observer, and Factory patterns.",
    "The Singleton pattern ensures that a class has only one instance and provides a global point of access to it.",
    "The Observer pattern defines a one-to-many dependency between objects, where a change in one object triggers updates in others.",
    "The Factory pattern provides an interface for creating objects but allows subclasses to alter the type of objects that will be created.",
    "The Strategy pattern defines a family of algorithms, encapsulates each one, and makes them interchangeable without altering the code that uses them.",
    "The Adapter pattern allows incompatible interfaces to work together by wrapping an existing interface with a new one.",
    "The Decorator pattern adds behavior to individual objects, either statically or dynamically, without affecting the behavior of other objects.",
    "The Composite pattern lets clients treat individual objects and compositions of objects uniformly.",
    "In event-driven programming, events trigger code execution, often used in graphical user interfaces (GUIs) and asynchronous programming.",
    "Asynchronous programming involves executing tasks concurrently without blocking the main thread, often using callbacks, promises, or async/await syntax.",
    "Concurrency refers to multiple tasks making progress simultaneously, while parallelism refers to tasks running at the same time on multiple processors.",
    "Multithreading allows multiple threads to run concurrently within a single process, improving the performance of certain applications.",
    "Synchronization ensures that multiple threads or processes can safely access shared resources without causing data corruption or inconsistency.",
    "Deadlock occurs when two or more threads are waiting for each other to release resources, causing them to be stuck indefinitely.",
    "Race conditions happen when the outcome of a program depends on the relative timing of uncontrollable events, often leading to unpredictable behavior.",
    "The Observer pattern is useful for implementing distributed event handling systems where components need to be updated in response to changes.",
    "The Proxy pattern provides a surrogate or placeholder for another object to control access to it.",
    "Dependency Injection (DI) is a technique to achieve Inversion of Control (IoC) by injecting dependencies into objects rather than creating them internally.",
    "The Inversion of Control (IoC) principle reverses the flow of control in a program, delegating responsibility to a framework or container.",
    "Inversion of Control containers manage the lifecycle and dependencies of objects, often used in frameworks to support dependency injection.",
    "Unit testing involves testing individual components or functions in isolation to ensure they work correctly.",
    "Integration testing verifies that different components of a system work together as expected.",
    "End-to-end testing involves testing an entire application or system from start to finish to ensure it meets requirements and functions correctly.",
    "Mock objects simulate the behavior of real objects in a controlled way, often used in unit testing to isolate components.",
    "Continuous Integration (CI) involves automatically building and testing code changes to detect issues early in the development process.",
    "Continuous Deployment (CD) automates the release of code changes to production environments, enabling frequent and reliable software releases.",
    "Version control systems, like Git, manage changes to source code over time, allowing collaboration and tracking of modifications.",
    "Branching and merging in version control systems help manage different lines of development and integrate changes from multiple contributors.",
    "A commit in version control systems represents a snapshot of changes made to the codebase, along with a message describing the changes.",
    "A pull request (or merge request) is a request to merge code changes from one branch into another, often reviewed by other team members.",
    "Code review involves examining code changes for quality, correctness, and adherence to coding standards before merging them into the main codebase.",
    "Refactoring is the process of restructuring existing code to improve its readability, maintainability, or performance without changing its external behavior.",
    "Code smells are signs that indicate potential issues or areas for improvement in code, such as long methods or large classes.",
    "The Single Responsibility Principle (SRP) states that a class should have only one reason to change, promoting modular and maintainable design.",
    "The Open/Closed Principle (OCP) states that software entities should be open for extension but closed for modification, supporting extensibility without altering existing code.",
    "The Liskov Substitution Principle (LSP) ensures that derived classes can be substituted for their base classes without affecting the correctness of the program.",
    "The Interface Segregation Principle (ISP) suggests that clients should not be forced to depend on interfaces they do not use, promoting smaller, more focused interfaces.",
    "The Dependency Inversion Principle (DIP) advocates for high-level modules to depend on abstractions rather than concrete implementations, reducing coupling.",
    "Object-relational mapping (ORM) tools automate the interaction between object-oriented programming languages and relational databases.",
    "A relational database organizes data into tables with rows and columns, using SQL (Structured Query Language) for querying and managing data.",
    "Normalization in relational databases involves organizing data to reduce redundancy and improve data integrity.",
    "Indexing improves the speed of data retrieval operations by creating data structures that allow for faster searching and sorting.",
    "A transaction in a database is a sequence of operations that are executed as a single unit of work, ensuring atomicity, consistency, isolation, and durability (ACID properties).",
    "Database normalization involves dividing a database into two or more tables and defining relationships between them to minimize redundancy.",
    "Data warehousing involves collecting and managing data from various sources to provide meaningful insights and support business intelligence activities.",
    "Big Data refers to large and complex data sets that require advanced tools and techniques for processing, analysis, and storage.",
    "NoSQL databases provide flexible schema designs and are optimized for specific types of data or use cases, such as document stores, key-value stores, and graph databases.",
    "A web API (Application Programming Interface) defines a set of rules for interacting with web services, allowing different applications to communicate over HTTP.",
    "REST (Representational State Transfer) is an architectural style for designing networked applications, using HTTP methods to interact with resources represented by URIs.",
    "GraphQL is a query language for APIs that allows clients to request specific data and receive exactly what they need in a single response.",
    "WebSockets provide a full-duplex communication channel over a single, long-lived connection, enabling real-time data exchange between clients and servers.",
    "Microservices architecture breaks down a large application into smaller, independent services that communicate with each other over well-defined interfaces.",
    "Containerization involves packaging applications and their dependencies into containers, which can run consistently across different environments.",
    "Docker is a popular containerization platform that allows developers to build, deploy, and manage containers easily.",
    "Kubernetes is an open-source platform for automating the deployment, scaling, and management of containerized applications.",
    "Serverless computing abstracts away infrastructure management, allowing developers to focus on writing code while the cloud provider handles scaling and resource management.",
    "A load balancer distributes incoming network traffic across multiple servers to ensure high availability and reliability of applications.",
    "Caching stores frequently accessed data in memory to reduce retrieval times and improve performance.",
    "Content Delivery Networks (CDNs) distribute content across multiple geographically dispersed servers to improve access speed and reduce latency.",
    "Encryption protects data by converting it into a secure format that can only be decrypted by authorized parties using a key.",
    "Authentication verifies the identity of a user or system, while authorization determines the access rights or permissions of an authenticated entity.",
    "OAuth is an authorization framework that allows third-party applications to access user resources without exposing user credentials.",
    "JSON (JavaScript Object Notation) is a lightweight data-interchange format that is easy for humans to read and write, and easy for machines to parse and generate.",
    "XML (eXtensible Markup Language) is a markup language used for encoding documents in a format that is both human-readable and machine-readable.",
    "Regular expressions (regex) are patterns used to match and manipulate text based on specific search criteria.",
    "Designing user interfaces involves creating layouts and interactions that enhance the user experience and usability of software applications.",
    "User Experience (UX) design focuses on improving the overall experience of users when interacting with a product, including usability, accessibility, and satisfaction.",
    "User Interface (UI) design involves the creation of visual elements and layouts that users interact with in a software application.",
    "Responsive design ensures that a web application or website adjusts its layout and content to provide an optimal viewing experience across different devices and screen sizes.",
    "Version control systems like Git allow multiple developers to collaborate on code by managing changes, branching, and merging.",
    "Agile software development emphasizes iterative development, collaboration, and flexibility to adapt",
    "All Turing-complete languages are capable of performing any computation that can be described algorithmically, given enough time and resources.",
    "The Church-Turing thesis posits that any computation that can be performed by an algorithm can be computed by a Turing machine.",
    "A Turing machine is an abstract mathematical model of computation that consists of an infinite tape, a head, and a set of states and rules.",
    "Algorithm complexity is often analyzed using Big O notation to describe the growth rate of an algorithm's running time or space requirements.",
    "The P vs NP problem is one of the most famous unsolved problems in computer science, questioning whether every problem whose solution can be verified quickly (in polynomial time) can also be solved quickly (in polynomial time).",
    "A data structure is a way of organizing and storing data to enable efficient access and modification, such as arrays, linked lists, stacks, and queues.",
    "Sorting algorithms, such as quicksort, mergesort, and heapsort, arrange elements in a specific order, commonly in ascending or descending order.",
    "A graph is a collection of nodes (vertices) connected by edges, used to model relationships and structures in various domains, such as social networks and routing algorithms.",
    "Graph algorithms, like Dijkstra's and A* search, are used to find shortest paths, minimum spanning trees, and other properties in graphs.",
    "A binary tree is a data structure where each node has at most two children, commonly used in search and sorting algorithms.",
    "Dynamic programming is a method for solving problems by breaking them down into simpler subproblems and storing the results to avoid redundant calculations.",
    "The divide and conquer strategy involves breaking a problem into smaller subproblems, solving each subproblem independently, and combining the results.",
    "In computational theory, complexity classes categorize problems based on their computational difficulty, such as P, NP, NP-complete, and NP-hard.",
    "Computational complexity theory studies the resources required for solving computational problems, including time and space complexity.",
    "The halting problem is a decision problem that asks whether a given program will halt or run indefinitely; it is proven to be undecidable for Turing machines.",
    "Cryptography is the study of securing information through encoding techniques to protect data from unauthorized access or tampering.",
    "Public key cryptography uses a pair of keys (public and private) to encrypt and decrypt data, enabling secure communication over untrusted networks.",
    "Symmetric encryption uses the same key for both encryption and decryption, while asymmetric encryption uses a pair of keys.",
    "Hash functions generate a fixed-size output (hash) from variable-sized input data, commonly used for data integrity checks and digital signatures.",
    "The theory of automata studies abstract machines (automata) and the problems they can solve, including finite automata, pushdown automata, and Turing machines.",
    "A finite automaton is a theoretical model of computation with a limited amount of memory, used to recognize regular languages.",
    "A context-free grammar generates context-free languages, which can be parsed using algorithms like the CYK algorithm and are used in programming languages.",
    "Formal languages and grammars provide a framework for defining and analyzing syntactical structures in programming languages and other systems.",
    "The von Neumann architecture is a computer architecture model that consists of a central processing unit (CPU), memory, and input/output devices, with a shared memory for data and instructions.",
    "The fetch-execute cycle is the basic operation cycle of a CPU, consisting of fetching an instruction from memory, decoding it, executing it, and then storing the result.",
    "Machine code is the lowest-level programming language, consisting of binary instructions that are directly executed by the CPU.",
    "Assembly language is a low-level programming language that provides a symbolic representation of machine code instructions, making it easier to write and understand.",
    "An operating system manages hardware resources, provides a user interface, and enables software applications to run, including functions like process management, memory management, and file systems.",
    "Virtual memory allows a computer to use disk storage to extend the available memory, creating the illusion of a larger physical memory.",
    "A file system organizes and manages data on storage devices, providing mechanisms for creating, reading, writing, and deleting files and directories.",
    "Networking protocols define the rules and conventions for communication between computers over a network, such as TCP/IP, HTTP, and FTP.",
    "The OSI model is a conceptual framework for understanding network protocols, consisting of seven layers: physical, data link, network, transport, session, presentation, and application.",
    "IP addresses identify devices on a network, allowing them to send and receive data, while domain names provide human-readable addresses mapped to IP addresses through DNS.",
    "The client-server model is a network architecture where clients request services or resources from servers, which provide the requested data or functionality.",
    "Distributed systems involve multiple computers working together to achieve a common goal, often requiring coordination, communication, and synchronization.",
    "Cloud computing provides on-demand access to computing resources and services over the internet, enabling scalable and flexible solutions.",
    "Data mining involves analyzing large datasets to discover patterns, trends, and useful information using techniques like clustering, classification, and regression.",
    "Machine learning is a branch of artificial intelligence that focuses on developing algorithms and models that enable computers to learn from and make predictions based on data.",
    "Neural networks are computational models inspired by the human brain, consisting of interconnected nodes (neurons) that process and learn from data.",
    "Deep learning is a subset of machine learning that uses multi-layered neural networks to model and solve complex problems, such as image and speech recognition.",
    "Natural language processing (NLP) enables computers to understand, interpret, and generate human language, with applications in chatbots, translation, and sentiment analysis.",
    "Computer vision is the field of study that enables computers to interpret and understand visual information from the world, such as images and videos.",
    "Algorithms are step-by-step procedures or formulas for solving problems or performing tasks, essential for software development and data processing.",
    "Software engineering involves applying engineering principles to the design, development, testing, and maintenance of software systems to ensure quality and reliability.",
    "The software development lifecycle (SDLC) encompasses stages like requirements analysis, design, implementation, testing, deployment, and maintenance.",
    "Agile methodologies emphasize iterative development, collaboration, and flexibility, with frameworks like Scrum and Kanban to manage and improve the development process.",
    "Version control systems, like Git, help manage changes to code, track revisions, and facilitate collaboration among developers.",
    "Database normalization involves organizing data to reduce redundancy and improve data integrity, often through techniques like First Normal Form (1NF) and Second Normal Form (2NF).",
    "Relational databases use tables with rows and columns to represent and manage data, with SQL (Structured Query Language) used for querying and manipulating data.",
    "NoSQL databases provide flexible schema designs and are optimized for specific types of data or use cases, such as document stores, key-value stores, and graph databases.",
    "Big O notation describes the time or space complexity of an algorithm in terms of its input size, providing an upper bound on the growth rate.",
    "Recursion is a technique where a function calls itself to solve a problem by breaking it down into smaller, more manageable subproblems.",
    "Dynamic programming is a method for solving problems by breaking them down into simpler subproblems and storing the results to avoid redundant computations.",
    "The principle of divide and conquer involves breaking a problem into smaller subproblems, solving each subproblem independently, and combining the results.",
    "Computational complexity theory studies the resources required for solving computational problems, including time and space complexity.",
    "The halting problem is a decision problem that asks whether a given program will halt or run indefinitely; it is proven to be undecidable for Turing machines.",
    "Computational theory explores the limits of what can be computed and the efficiency of algorithms, including concepts like decidability and tractability.",
    "Concurrency involves executing multiple tasks simultaneously, often requiring mechanisms for synchronization and communication to avoid conflicts.",
    "Parallelism refers to performing multiple operations or tasks at the same time, leveraging multiple processors or cores to improve performance.",
    "Synchronization mechanisms, such as mutexes and semaphores, ensure that multiple threads or processes can safely access shared resources without causing data corruption.",
    "Deadlock occurs when two or more threads are waiting for each other to release resources, causing them to be stuck indefinitely.",
    "Race conditions happen when the outcome of a program depends on the relative timing of uncontrollable events, often leading to unpredictable behavior.",
    "A debugger is a tool that helps developers identify, analyze, and fix bugs or issues in their code by providing features like breakpoints, step execution, and variable inspection.",
    "Profiling is the process of measuring the performance of a program to identify bottlenecks and optimize code for better efficiency.",
    "Software testing involves verifying that software functions as intended and meets specified requirements, using techniques like unit testing, integration testing, and system testing.",
    "Code review is the practice of examining code changes by other developers to ensure quality, correctness, and adherence to coding standards before merging them into the main codebase.",
    "Refactoring is the process of restructuring existing code to improve its readability, maintainability, or performance without changing its external behavior.",
    "Design patterns are reusable solutions to common software design problems, such as Singleton, Factory, and Observer patterns, providing proven strategies for addressing recurring issues.",
    "The Singleton pattern ensures that a class has only one instance and provides a global point of access to it, often used for managing shared resources.",
]
NATURE = [
    "The Amazon Rainforest is the largest tropical rainforest in the world, covering approximately 5.5 million square kilometers.",
    "Around 20% of the world's oxygen is produced by the Amazon Rainforest through photosynthesis.",
    "Mount Everest, the highest mountain in the world, stands at 8,848 meters (29,029 feet) above sea level.",
    "The Great Barrier Reef is the largest coral reef system in the world, stretching over 2,300 kilometers (1,430 miles) along the coast of Australia.",
    "The Sahara Desert is the largest hot desert in the world, covering about 9 million square kilometers (3.5 million square miles).",
    "Polar bears have black skin under their white fur, which helps them absorb and retain heat from the sun.",
    "A blue whale is the largest animal ever known to have existed, with some individuals reaching lengths of up to 30 meters (98 feet) and weights of up to 200 tons.",
    "The Grand Canyon is approximately 277 miles (446 kilometers) long, up to 18 miles (29 kilometers) wide, and over a mile (1.6 kilometers) deep.",
    "Sequoia trees, also known as redwoods, are among the tallest trees in the world, with some reaching heights of over 300 feet (91 meters).",
    "The deepest part of the ocean is the Mariana Trench, which reaches a depth of about 36,000 feet (10,973 meters).",
    "Antarctica is the driest, windiest, and coldest continent on Earth, with temperatures that can drop below -60°C (-76°F).",
    "Lightning is hotter than the surface of the sun, with temperatures reaching up to 30,000 Kelvin (53,540°F).",
    "The world's largest volcano is Mauna Loa in Hawaii, which covers an area of about 2,035 square miles (5,271 square kilometers).",
    "A single tree can absorb up to 48 pounds (22 kilograms) of carbon dioxide per year and release oxygen in return.",
    "The Monarch butterfly migrates up to 3,000 miles (4,800 kilometers) each year from Canada and the United States to central Mexico.",
    "Honeybees have to collect nectar from about 2 million flowers to produce one pound of honey.",
    "The Sahara Desert is home to the world’s largest hot desert, where daytime temperatures can reach up to 50°C (122°F).",
    "The Nile River is the longest river in the world, stretching approximately 6,650 kilometers (4,130 miles) from its source to its mouth.",
    "The Amazon River is the largest river in the world by discharge volume, carrying more water than the next seven largest rivers combined.",
    "An adult giraffe's neck is about 6 feet (1.8 meters) long and weighs up to 550 pounds (250 kilograms).",
    "The cheetah is the fastest land animal, capable of reaching speeds of up to 75 miles per hour (120 kilometers per hour) in short bursts.",
    "Octopuses have three hearts and blue blood, which helps them survive in low-oxygen environments.",
    "Jellyfish have been around for more than 500 million years, making them one of the oldest living creatures on Earth.",
    "The Arctic Tundra is home to unique flora and fauna adapted to extreme cold, including the Arctic fox and polar bear.",
    "Penguins are flightless birds that are well adapted to swimming, with some species diving to depths of over 500 meters (1,640 feet).",
    "The giant panda primarily eats bamboo, consuming up to 40 pounds (18 kilograms) of it daily.",
    "Coral reefs support a diverse array of marine life, providing habitat for about 25% of all marine species.",
    "A group of flamingos is called a 'flamboyance,' and they are known for their distinctive pink coloration, which comes from their diet.",
    "The cheetah's acceleration is faster than a sports car, allowing it to reach top speeds in just a few seconds.",
    "The Komodo dragon is the largest living lizard, growing up to 10 feet (3 meters) in length and weighing up to 150 pounds (68 kilograms).",
    "Sloths are incredibly slow-moving mammals, spending up to 20 hours a day sleeping and moving at an average speed of about 0.03 miles per hour (0.05 kilometers per hour).",
    "The Baobab tree, known as the 'Tree of Life,' can store up to 32,000 gallons (121,000 liters) of water in its trunk to survive droughts.",
    "A single teaspoon of soil can contain billions of microorganisms, including bacteria, fungi, and protozoa.",
    "The Saguaro cactus, native to the Sonoran Desert, can grow to be over 40 feet (12 meters) tall and live for over 150 years.",
    "Lightning strikes the Earth about 100 times every second, resulting in about 8.6 million strikes each day.",
    "The peregrine falcon is the fastest bird, reaching speeds of over 240 miles per hour (386 kilometers per hour) during its hunting dive.",
    "Some species of bamboo can grow up to 35 inches (91 centimeters) in a single day, making it one of the fastest-growing plants on Earth.",
    "The Amazon Rainforest is home to more than 2.5 million different insect species, along with a vast diversity of plants and animals.",
    "The Greenland shark is one of the longest-living vertebrates, with some individuals estimated to be over 400 years old.",
    "The Mantis shrimp has the most complex eyes in the animal kingdom, with 16 types of color receptors compared to the three in human eyes.",
    "The world's largest living organism is the honey fungus in Oregon, which covers an area of over 2,385 acres (965 hectares) underground.",
    "The deep ocean is home to bioluminescent organisms that produce their own light through chemical reactions, creating stunning underwater displays.",
    "Giraffes have long tongues, up to 18 inches (45 centimeters) in length, which they use to grasp leaves from tall trees.",
    "Hummingbirds are the only birds that can fly backward, thanks to their unique wing structure and rapid wing beats.",
    "Seals have the ability to hold their breath for extended periods while diving, with some species reaching depths of over 1,500 feet (460 meters).",
    "The European swallow is known for its migratory patterns, traveling between Europe and Africa each year to escape the cold winters.",
    "The world's smallest mammal is the bumblebee bat, with a wingspan of about 5.7 inches (14.5 centimeters) and a weight of less than 2 grams.",
    "The Amazon Rainforest produces about 6% of the world's oxygen and is crucial for regulating the global climate.",
    "Cheetahs have distinctive black 'tear marks' running from their eyes down to their mouths, which help reduce glare from the sun and improve their vision.",
    "The dragonfly is one of the oldest insects, with fossil records dating back over 300 million years.",
    "Coral reefs are highly sensitive to changes in water temperature, with coral bleaching occurring when they expel the symbiotic algae living in their tissues.",
    "The African elephant is the largest land animal, with males weighing up to 12,000 pounds (5,443 kilograms) and standing up to 13 feet (4 meters) tall at the shoulder.",
    "The golden poison dart frog is one of the most toxic animals in the world, with enough poison on its skin to kill several humans.",
    "The Bengal tiger, the largest tiger subspecies, is native to India and has distinctive orange and black stripes that help it blend into its natural habitat.",
    "Kangaroos are native to Australia and are known for their powerful hind legs, which allow them to leap up to 30 feet (9 meters) in a single bound.",
    "The Andean condor is one of the largest flying birds, with a wingspan that can exceed 10 feet (3 meters).",
    "The Great Wall of China is often visible from space, but the tallest man-made structure on Earth is the Burj Khalifa in Dubai, standing at 828 meters (2,717 feet).",
    "Oceans cover about 71% of the Earth's surface, with the Pacific Ocean being the largest and deepest of the world's oceans.",
    "Mount Kilimanjaro in Tanzania is the highest free-standing mountain in the world, rising about 5,895 meters (19,341 feet) above sea level.",
    "Hummingbirds have the highest metabolism of any animal, with their heart rate reaching up to 1,200 beats per minute during flight.",
    "The Caspian Sea is the largest enclosed inland body of water, with an area of approximately 371,000 square kilometers (143,000 square miles).",
    "The Redwood National and State Parks in California are home to some of the tallest and oldest trees in the world, with some redwoods reaching over 2,000 years old.",
    "An adult whale shark can grow to lengths of over 40 feet (12 meters) and weigh up to 20 tons, making it the largest fish species.",
    "The Antarctic Ice Sheet contains about 60% of the world's fresh water, and its melting contributes to global sea level rise.",
    "A coral reef is often called the 'rainforest of the sea' because of its high biodiversity and the vital role it plays in marine ecosystems.",
]
MATH = [
    "Zero (0) is the only number that cannot be represented by Roman numerals.",
    "Pi (π) is an irrational number, meaning it cannot be expressed as a simple fraction, and its decimal representation goes on forever without repeating.",
    "The Fibonacci sequence is a series of numbers where each number is the sum of the two preceding ones, starting from 0 and 1. It appears frequently in nature, such as in the arrangement of leaves and the branching of trees.",
    "The number e (approximately 2.71828) is the base of the natural logarithm and is also an irrational number. It arises in many areas of mathematics, particularly in calculus and complex analysis.",
    "A prime number is a natural number greater than 1 that has no positive divisors other than 1 and itself. Examples include 2, 3, 5, and 7.",
    "The sum of the angles in any triangle is always 180 degrees.",
    "Euler's formula, e^(iπ) + 1 = 0, is often celebrated for its beauty as it links five of the most important mathematical constants: e, i, π, 1, and 0.",
    "The Riemann Hypothesis is an unsolved problem in mathematics concerning the distribution of prime numbers and the zeros of the Riemann zeta function.",
    "The number 1 is neither prime nor composite. Prime numbers are defined as having exactly two distinct positive divisors, and composite numbers have more than two.",
    "A factorial, denoted as n!, is the product of all positive integers from 1 to n. For example, 5! = 5 × 4 × 3 × 2 × 1 = 120.",
    "The Pythagorean theorem states that in a right-angled triangle, the square of the length of the hypotenuse is equal to the sum of the squares of the other two sides.",
    "The sum of the first n positive integers is given by the formula n(n + 1) / 2.",
    "Imaginary numbers are numbers that, when squared, give a negative result. The unit imaginary number is denoted as i, where i^2 = -1.",
    "The Golden Ratio, denoted by φ (phi), is approximately 1.61803. It is a special number that appears in various aspects of art, architecture, and nature.",
    "The number 1729 is known as the Hardy-Ramanujan number. It is the smallest number that can be expressed as the sum of two cubes in two different ways: 1^3 + 12^3 and 9^3 + 10^3.",
    "A Mersenne prime is a prime number that can be written in the form 2^p - 1, where p is also a prime number. Examples include 3, 7, and 31.",
    "A palindrome number reads the same backward as forward, such as 121 or 1331.",
    "In probability theory, the expected value is a measure of the center of a probability distribution, representing the average outcome if an experiment were repeated many times.",
    "The law of large numbers states that as the number of trials in a random experiment increases, the sample mean will converge to the expected value.",
    "A fractal is a complex geometric shape that can be split into parts, each of which is a reduced-scale copy of the whole, exhibiting self-similarity.",
    "The Collatz conjecture is an unsolved problem in mathematics that involves a sequence defined by a simple iterative process, where the conjecture claims that starting from any positive integer, the sequence will always eventually reach 1.",
    "In combinatorics, a permutation is an arrangement of objects in a specific order, while a combination is a selection of objects without regard to order.",
    "A group in abstract algebra is a set equipped with an operation that combines any two elements to form another element of the set, satisfying four fundamental properties: closure, associativity, identity, and invertibility.",
    "The Euclidean algorithm is an efficient method for finding the greatest common divisor (GCD) of two integers.",
    "The concept of limits is fundamental to calculus and is used to define derivatives and integrals.",
    "The Fundamental Theorem of Calculus states that differentiation and integration are inverse processes, linking the two main concepts of calculus.",
    "A vector space is a collection of vectors that can be added together and multiplied by scalars, adhering to certain axioms.",
    "In linear algebra, the determinant of a square matrix provides important properties about the matrix, including whether it is invertible.",
    "A matrix is a rectangular array of numbers arranged in rows and columns, used in various mathematical computations, including solving systems of linear equations.",
    "The term 'asymptote' refers to a line that a graph approaches but never actually reaches, typically used in the context of rational functions.",
    "A polynomial is an expression consisting of variables and coefficients, combined using addition, subtraction, and multiplication, but not division by variables.",
    "The degree of a polynomial is the highest power of the variable in the polynomial.",
    "The fundamental theorem of algebra states that every non-constant polynomial equation has at least one complex root.",
    "The set of real numbers includes all rational and irrational numbers and can be visualized as a continuous line extending infinitely in both directions.",
    "The Cantor set is a fractal created by repeatedly removing the middle third of a line segment, resulting in a set with zero length but an uncountably infinite number of points.",
    "The Gaussian distribution, or normal distribution, is a probability distribution that is symmetric around its mean, with data near the mean being more frequent in occurrence.",
    "The Monty Hall problem is a probability puzzle based on a game show scenario, illustrating the counterintuitive result of switching choices to increase chances of winning.",
    "In game theory, the Nash equilibrium is a concept where no player can benefit by changing their strategy while the other players keep theirs unchanged.",
    "The binomial theorem describes the algebraic expansion of powers of a binomial, expressed as (a + b)^n.",
    "In set theory, a set is a collection of distinct objects, considered as an object in its own right.",
    "Cantor's diagonal argument is a technique used to show that some infinite sets are uncountably infinite, meaning they cannot be put into a one-to-one correspondence with the natural numbers.",
    "A number is a perfect square if it is the square of an integer. For example, 16 is a perfect square because it equals 4^2.",
    "The Euler characteristic is a topological invariant used to describe the shape or structure of a geometrical object, calculated as V - E + F, where V is the number of vertices, E is the number of edges, and F is the number of faces.",
    "The Sieve of Eratosthenes is an ancient algorithm used to find all prime numbers up to a specified integer by iteratively marking the multiples of each prime.",
    "The Riemann zeta function is a complex function that plays a key role in number theory and is related to the distribution of prime numbers.",
    "A polyhedron is a solid in three dimensions with flat polygonal faces, straight edges, and vertices. Examples include cubes and pyramids.",
    "In topology, a Möbius strip is a surface with only one side and one edge, which can be created by giving a strip of paper a half-twist and then joining the ends.",
    "The law of sines and the law of cosines are trigonometric identities that relate the sides and angles of a triangle.",
    "A continuous function is a function where small changes in the input result in small changes in the output, without sudden jumps or breaks.",
    "The Poincaré conjecture, now proven and known as the Poincaré theorem, was a famous problem in topology that dealt with the characterization of three-dimensional spheres.",
    "The Fibonacci spiral approximates the golden spiral and is found in various natural phenomena, including the arrangement of seeds in a sunflower.",
    "A bijective function is a one-to-one correspondence between elements of two sets, where every element of the first set maps to a unique element of the second set and vice versa.",
    "In probability, the law of total probability provides a way to calculate the probability of an event by considering all possible ways the event can occur.",
    "The principle of inclusion-exclusion is a combinatorial method used to find the size of the union of overlapping sets by subtracting the sizes of the intersections.",
    "A convex polygon is a polygon where all interior angles are less than 180 degrees, and any line segment connecting two points inside the polygon lies entirely within it.",
    "A non-Euclidean geometry is any geometry that is based on axioms different from those of Euclidean geometry, including hyperbolic and elliptic geometries.",
    "The Heisenberg uncertainty principle in quantum mechanics states that certain pairs of physical properties, like position and momentum, cannot both be precisely measured simultaneously.",
    "In graph theory, a Hamiltonian path visits each vertex exactly once, while a Hamiltonian cycle visits each vertex exactly once and returns to the starting vertex.",
    "The Traveling Salesman Problem is a classic optimization problem where the goal is to find the shortest possible route that visits a set of cities and returns to the origin city.",
    "The concept of entropy in information theory quantifies the amount of uncertainty or randomness in a set of data, with higher entropy indicating greater unpredictability.",
    "A Markov chain is a stochastic process where the probability of transitioning from one state to another depends only on the current state, not on the sequence of events that preceded it.",
]


FORTUNE = [
   "You will find a surprise in the next 24 hours.",
   "A new friend will bring you joy soon.",
   "Something you lost will be found today.",
   "Expect a pleasant surprise in the mail.",
   "You will meet someone who inspires you.",
   "An unexpected adventure is on the horizon.",
   "You will solve a problem that has been bothering you.",
   "Good news will come from an old friend.",
   "A small kindness will bring great rewards.",
   "You are about to receive a compliment.",
   "You will discover a hidden talent.",
   "A positive change is coming your way.",
   "You will make a new friend this week.",
   "Your hard work will soon pay off.",
   "A creative idea will bring you success.",
   "You will have a memorable experience soon.",
   "Expect an exciting opportunity in the near future.",
   "A pleasant surprise is in store for you.",
   "You will achieve a goal you’ve set for yourself.",
   "Someone will bring you unexpected joy.",
   "Your generosity will be rewarded.",
   "You are about to embark on a new journey.",
   "A happy event is on the way.",
   "You will receive positive feedback soon.",
   "A new project will bring you satisfaction.",
   "Good fortune will come your way unexpectedly.",
   "You will enjoy a moment of serenity soon.",
   "Your creativity will shine brightly.",
   "An old friend will reach out to you.",
   "A surprise encounter will bring joy.",
   "You will find peace in a new place.",
   "Your optimism will lead to success.",
   "You will receive a thoughtful gift.",
   "A new opportunity is on the horizon.",
   "You will make a positive impact on someone’s life.",
   "Your dreams are closer to coming true.",
   "You will have a chance to showcase your talents.",
   "A fun and exciting day is ahead.",
   "You will enjoy a moment of clarity.",
   "A pleasant surprise will make your day.",
   "Your efforts will bring about a positive change.",
   "Someone will offer you valuable advice.",
   "You will find joy in a simple pleasure.",
   "A new friendship will blossom.",
   "You will experience a small but significant win.",
   "Your hard work will be recognized.",
   "You will discover something new about yourself.",
   "A positive change in your life is imminent.",
   "You will be pleasantly surprised by someone’s gesture.",
   "An exciting opportunity will come your way.",
   "Your kindness will be returned tenfold.",
   "You will achieve something you’ve been striving for.",
   "A fun event is in your near future.",
   "You will find inspiration in an unexpected place.",
   "A joyful occasion is approaching.",
   "You will receive good news from an unexpected source.",
   "A delightful surprise will come your way soon.",
   "You will have a reason to celebrate shortly.",
   "You are about to discover a new passion.",
   "A small change will bring great happiness.",
   "You will experience a moment of pure joy.",
   "A new chapter in your life is beginning.",
   "You will enjoy a pleasant surprise today.",
   "An exciting event will soon make you smile.",
   "You will achieve a personal goal soon.",
   "Someone will share good news with you.",
   "A fresh opportunity will come your way.",
   "Your creativity will bring you success.",
   "You will find joy in the little things.",
   "A positive change is about to happen in your life.",
   "You will receive a meaningful compliment.",
   "A fun and engaging experience is on the horizon.",
   "You will make a valuable new connection.",
   "Your efforts will be rewarded in an unexpected way.",
   "A pleasant surprise will brighten your day.",
   "You will have a chance to show off your skills.",
   "A small victory will lead to a larger one.",
   "You will enjoy a moment of happiness soon.",
   "An unexpected gift will bring you joy.",
   "A new adventure is just around the corner.",
   "You will make a positive change in your life.",
   "A delightful surprise is waiting for you.",
   "You will receive a boost of inspiration.",
   "Your positive attitude will lead to success.",
   "You will experience a joyful moment soon.",
   "A fun opportunity will come your way.",
   "You will find satisfaction in your achievements.",
   "An old friend will bring you good news.",
   "You will have a chance to share your talents.",
   "A new possibility will open up for you.",
   "You will experience a burst of creativity.",
   "A pleasant surprise is on the way.",
   "You will achieve something you’ve been dreaming of.",
   "A joyful event is approaching soon.",
   "You will receive a heartfelt gesture from someone special.",
   "A new friend will bring a positive change to your life.",
   "You will enjoy a moment of peace and contentment.",
   "An exciting opportunity is just around the corner.",
   "You will make a meaningful contribution.",
   "A happy surprise will make your day memorable.",
]


RANDOM = QUOTES + PROGRAMMING + MATH + NATURE + FORTUNE


def random(choices=RANDOM):
    """Convenience function to get random phrase.

    Returns:
    str: phrase
    """
    return choice(RANDOM)
